AWSTemplateFormatVersion: '2010-09-09'
Description: 'mailchimp

  Sample SAM Template for mailchimp

  '
Globals:
  Function:
    Timeout: 3
Outputs:
  HelloWorldApi:
    Description: API Gateway endpoint URL for Prod stage for Hello World function
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/
  SubscribeHandler:
    Description: Subscribe Handler Lambda Function ARN
    Value:
      Fn::GetAtt:
      - SubscribeHandler
      - Arn
  SubscribeHandlerIamRole:
    Description: Implicit IAM Role created for Subscribe Handler function
    Value:
      Fn::GetAtt:
      - SubscribeHandler
      - Arn
Resources:
  SubscribeHandler:
    Properties:
      CodeUri: s3://accimeesterlin-mailing-web/fcc387d8db94f84c2d7c40e5162e3d4f
      Description: Subscribe user to mailchimp mailing lists
      Environment:
        Variables:
          API_KEY: VALUE
          LIST_ID: VALUE
          USER_NAME: VALUE
      Events:
        HelloWorld:
          Properties:
            Method: post
            Path: /subscribe
          Type: Api
      FunctionName: SubscribeHandler
      Handler: app.lambdaHandler
      Runtime: nodejs8.10
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
