AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
    mailchimp

    Sample SAM Template for mailchimp
    
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
    Function:
        Timeout: 3


Resources:

    SubscribeHandler:
        Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
        Properties:
            CodeUri: ./
            Handler: app.lambdaHandler
            Runtime: nodejs8.10
            FunctionName: SubscribeHandler
            Description: Subscribe user to mailchimp mailing lists
            Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
                Variables:
                    LIST_ID: VALUE
                    API_KEY: VALUE
                    USER_NAME: VALUE

            Events:
                HelloWorld:
                    Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
                    Properties:
                        Path: /subscribe
                        Method: post

Outputs:

    HelloWorldApi:
      Description: "API Gateway endpoint URL for Prod stage for Hello World function"
      Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"

    SubscribeHandler:
      Description: "Subscribe Handler Lambda Function ARN"
      Value: !GetAtt SubscribeHandler.Arn

    SubscribeHandlerIamRole:
      Description: "Implicit IAM Role created for Subscribe Handler function"
      Value: !GetAtt SubscribeHandler.Arn
